In [102]:
#mathematical tool library import
import numpy as np

#to plot graph
import matplotlib.pyplot as pt

#to mange data set
import pandas as pd





In [103]:
#importing the data set using pandas
mydataset = pd.read_csv('new_mydata.csv')
print(mydataset)


       City   Age   Income Car_purchased
0   Colombo  44.0  72000.0            No
1  Nugegoda  27.0  48000.0           Yes
2     Kandy  30.0  54000.0            No
3  Nugegoda  38.0  61000.0            No
4     Kandy  40.0      NaN           Yes
5   Colombo  35.0  58000.0           Yes
6  Nugegoda   NaN  52000.0            No
7   Colombo  48.0  79000.0           Yes
8     Kandy  50.0  83000.0            No
9   Colombo  37.0  67000.0           Yes


In [104]:
X_independant = mydataset.iloc[ : , :-1].values
print(X_independant)

[['Colombo' 44.0 72000.0]
 ['Nugegoda' 27.0 48000.0]
 ['Kandy' 30.0 54000.0]
 ['Nugegoda' 38.0 61000.0]
 ['Kandy' 40.0 nan]
 ['Colombo' 35.0 58000.0]
 ['Nugegoda' nan 52000.0]
 ['Colombo' 48.0 79000.0]
 ['Kandy' 50.0 83000.0]
 ['Colombo' 37.0 67000.0]]


In [105]:
y_dependant = mydataset.iloc[ : , 3:].values
print(y_dependant)

[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


In [106]:
!pip install scikit-learn


In [107]:
import sklearn 

In [108]:
from sklearn.impute import SimpleImputer



In [109]:
imputerVariable = SimpleImputer(missing_values= np.nan, strategy= 'mean', fill_value= None,copy=True)
#print(imputerVariable)

In [110]:
imputerVariable.fit(X_independant[ : ,1:3])

SimpleImputer()

In [111]:
X_independant[:,1:3] = imputerVariable.transform(X_independant[:,1:3])
print(X_independant)

[['Colombo' 44.0 72000.0]
 ['Nugegoda' 27.0 48000.0]
 ['Kandy' 30.0 54000.0]
 ['Nugegoda' 38.0 61000.0]
 ['Kandy' 40.0 63777.77777777778]
 ['Colombo' 35.0 58000.0]
 ['Nugegoda' 38.77777777777778 52000.0]
 ['Colombo' 48.0 79000.0]
 ['Kandy' 50.0 83000.0]
 ['Colombo' 37.0 67000.0]]


In [112]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [113]:
labelencoderX_variable = LabelEncoder()
X_independant[:,0]=labelencoderX_variable.fit_transform(X_independant[:,0])

In [114]:
#OneHotEncoder = OneHotEncoder(categories=[0])

In [115]:
from sklearn.compose import ColumnTransformer
#X_independant = OneHotEncoder.fit_transform(X_independant).toarray()
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'),[0] )],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough')                                             # Leave the rest of the columns untouched

X_independant = ct.fit_transform(X_independant) 
print(X_independant) 

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [116]:
labelencoderY_variable = LabelEncoder()

In [118]:
y_dependant = labelencoderY_variable.fit_transform(y_dependant)
print(y_dependant)

[0 1 0 0 1 1 0 1 0 1]


In [119]:
 mydataset.info

<bound method DataFrame.info of        City   Age   Income Car_purchased
0   Colombo  44.0  72000.0            No
1  Nugegoda  27.0  48000.0           Yes
2     Kandy  30.0  54000.0            No
3  Nugegoda  38.0  61000.0            No
4     Kandy  40.0      NaN           Yes
5   Colombo  35.0  58000.0           Yes
6  Nugegoda   NaN  52000.0            No
7   Colombo  48.0  79000.0           Yes
8     Kandy  50.0  83000.0            No
9   Colombo  37.0  67000.0           Yes>